// The design settings a role starter starts with (buildResumeFromStarter), and a JSON Resume import
// (jsonResumeImport.js): the ATS-safe defaults with what its template brings (templateStyleDefaults).
import { templateStyleDefaults } from '../constants/templates.js';

export function getStarterSettings(template) {
  return {
    font: 'notosans',
    fontSize: 'normal',
    fontSizeBase: 11,
    fontSizeNameDelta: 8,
    fontSizeSectionDelta: 1,
    fontSizeEntryDelta: 0,
    lineHeight: 'normal',
    margins: 'normal',
    accentColor: '#374151',
    textColor: '#111111',
    headingStyle: 'ruled',
    sectionTitleCase: 'upper',
    dateFormat: 'MMM YYYY',
    sectionBorderWidth: 1,
    sectionBorderColor: '',
    headerAlign: 'left',
    headerLayout: 'stack',
    headerInlineGap: 8,
    contactStyle: 'icon',
    iconSet: 'filled',
    customContactIcons: {},
    contactCols: 1,
    contactLayout: 'justify',
    photoShape: 'circle',
    photoSize: 'md',
    photoBorder: 'accent',
    photoHeight: 'match',
    photoTextAlign: 'center',
    showHeaderBorder: false,
    headerBorderWidth: 2,
    customFont: '',
    iconSize: 11,
    lineHeightValue: 1.5,
    sectionGap: 16,
    itemGap: 8,
    marginH: 18,
    marginV: 14,
    sidebarBg: '#1e293b',
    headerTextColor: '#ffffff',
    nameColor: '',
    jobTitleColor: '',
    ...templateStyleDefaults(template),
  };
}
