#!/usr/bin/env python3
"""Write docs/tracking/fixes3/R4-TRACKER.md from the Round 4 cluster reports (docs/tracking/fixes3/reports/*.json).

Status: fixed / partial → ⏸ (on the work branch) until the commit is on master, then ✅; already-fixed ✅;
not-a-bug / duplicate / known-limit ✖; not-fixed 🔴. usage: r4_tracker.py [--deployed <master sha>]
"""
import glob, json, os, subprocess, sys

os.chdir(subprocess.run(['git', 'rev-parse', '--show-toplevel'], capture_output=True, text=True).stdout.strip() or '.')
deployed = sys.argv[sys.argv.index('--deployed') + 1] if '--deployed' in sys.argv else None


def on_master(commits):
    if not deployed or not commits:
        return False
    return all(subprocess.run(['git', 'merge-base', '--is-ancestor', c, deployed], capture_output=True).returncode == 0
               for c in commits)


rows = []
for f in sorted(glob.glob('docs/tracking/fixes3/reports/r4-*.json')):
    rep = json.load(open(f, encoding='utf-8'))
    for r in rep['rows']:
        o = r.get('outcome', '')
        if o in ('fixed', 'partial'):
            st = ('✅' if on_master(r.get('commits')) else '⏸') + (' Fixed' if o == 'fixed' else ' Partly fixed')
        elif o == 'already-fixed':
            st = '✅ Already fixed'
        elif o in ('not-a-bug', 'duplicate', 'known-limit'):
            st = '✖ ' + o.replace('-', ' ').capitalize()
        else:
            st = '🔴 ' + o
        cell = lambda s: (s or '').replace('|', '\\|').replace('\n', ' ')
        rows.append((r['id'], rep['cluster'], st, ', '.join(f'`{c}`' for c in r.get('commits') or []) or '—',
                     ', '.join(r.get('tests') or []) or '—', cell(r.get('summary')), cell(r.get('remaining'))))

count = {}
for r in rows:
    k = r[2].split(' ')[0]
    count[k] = count.get(k, 0) + 1
out = ['# Round 4 tracker (generated by docs/tracking/tools/r4_tracker.py — do not edit by hand)', '',
       f'{len(rows)} rows · ' + ' · '.join(f'{k} {v}' for k, v in sorted(count.items())) +
       (f' · deployed = `{deployed}`' if deployed else ' · none on master yet'), '',
       '| ID | Cluster | Status | Commits | Tests | Now | Left |', '|---|---|---|---|---|---|---|']
out += ['| ' + ' | '.join(r) + ' |' for r in rows]
open('docs/tracking/fixes3/R4-TRACKER.md', 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print(out[2])
