// Pulls open roles from each company's public ATS board, keeps UI / Node / Java roles in the
// wanted region, and writes jobs.json + JOBS.md.  Usage: node crawl.mjs [india|us|canada|europe]
import { readFileSync, writeFileSync } from 'node:fs';
import { ATS } from './ats.mjs';

const region = process.argv[2] ?? 'india';
const REGION_RX = {
  india: /india|bengaluru|bangalore|hyderabad|pune|mumbai|gurgaon|gurugram|noida|delhi|chennai|kolkata|ahmedabad|remote.*india/i,
  us: /\b(usa?|united states)\b|, (ca|ny|wa|tx|ma|il)\b|san francisco|new york|seattle|austin|boston|remote.*(us|united states)/i,
  canada: /canada|toronto|vancouver|montreal|ottawa|calgary/i,
  europe: /europe|london|uk\b|united kingdom|berlin|germany|amsterdam|netherlands|dublin|ireland|paris|france|spain|poland|sweden|zurich|switzerland/i,
}[region];

// Order matters: first match wins. Senior/manager titles are kept; tagged so you can filter.
const TRACKS = [
  ['java', /\b(java|spring ?boot|spring)\b(?!script)/i],
  ['node', /\b(node(\.?js)?|mern|pern|express)\b/i],
  ['ui', /\b(front[- ]?end|ui (engineer|developer)|ui\/ux engineer|react|angular|web (ui )?developer|ui engineer|javascript|typescript)\b/i],
  ['fullstack', /\bfull[- ]?stack\b/i],
];
const ENG = /\b(engineer|developer|sde|programmer|architect|software|swe)\b/i;
const DESC_TRACKS = [
  ['java', /\b(java|spring ?boot|hibernate|microservices? in java)\b/gi],
  ['node', /\b(node\.?js|express\.?js|nestjs|mern|pern)\b/gi],
  ['ui', /\b(react(\.?js)?|angular|vue|next\.?js|css3?|front[- ]?end)\b/gi],
];
const NOISE = /\b(intern|recruit|sales|marketing|designer|analyst|support|qa\b|sdet|data scientist|devops|sre|ios|android|manager of|director|vp\b)/i;
const SENIORITY = (t) => /\b(staff|principal|architect)\b/i.test(t) ? 'staff+' : /\b(sr|senior|lead)\b/i.test(t) ? 'senior' : /\b(sde[- ]?1|junior|associate|graduate|fresher|entry)\b/i.test(t) ? 'junior' : /\b(sde[- ]?(2|ii)|engineer ii|developer ii)\b/i.test(t) ? 'mid' : 'unspecified';

const companies = JSON.parse(readFileSync(new URL('./companies.json', import.meta.url), 'utf8'));
const jobs = [], status = [];
for (const c of companies) {
  if (!c.ats) { status.push({ ...c, state: 'no-public-board' }); continue; }
  try {
    const all = (await ATS[c.ats].list(c.slug)) ?? [];
    let kept = 0;
    for (const j of all) {
      if (!(REGION_RX.test(j.location) || /^\d+ locations?$/i.test(j.location)) || NOISE.test(j.title)) continue;
      if (!ENG.test(j.title)) continue;
      const byTitle = TRACKS.find(([, rx]) => rx.test(j.title));
      const byDesc = !byTitle && DESC_TRACKS.map(([t, rx]) => [t, (j.desc ?? '').match(rx)?.length ?? 0]).sort((a, b) => b[1] - a[1])[0];
      const track = byTitle ? byTitle[0] : byDesc && byDesc[1] >= 2 ? byDesc[0] : 'other-eng';
      const { desc, ...rest } = j;
      jobs.push({ company: c.name, category: c.category, tier: c.tier, track, how: byTitle ? 'title' : track === 'other-eng' ? '-' : 'jd', level: SENIORITY(j.title), ...rest });
      kept++;
    }
    status.push({ ...c, state: 'ok', total: all.length, matched: kept });
  } catch (e) { status.push({ ...c, state: `error: ${e.message}` }); }
}

const crawled = new Date().toISOString().slice(0, 10);
writeFileSync(new URL(`./jobs-${region}.json`, import.meta.url), JSON.stringify({ crawled, region, jobs, status }, null, 1));

const md = [`# Open roles — ${region} (crawled ${crawled})`, '',
  'Auto-generated by `crawl.mjs` from public ATS boards. Do not edit. Companies without a public board are listed at the bottom.', ''];
for (const track of ['ui', 'node', 'java', 'fullstack', 'other-eng']) {
  const rows = jobs.filter((j) => j.track === track).sort((a, b) => a.tier - b.tier || a.company.localeCompare(b.company));
  md.push(`## ${track.toUpperCase()} — ${rows.length} roles`, '', '| Tier | Company | Category | Role | Level | Location | Tagged by |', '|---|---|---|---|---|---|---|');
  for (const j of rows) md.push(`| T${j.tier} | ${j.company} | ${j.category} | [${j.title.replace(/\|/g, '/')}](${j.url}) | ${j.level} | ${j.location.replace(/\|/g, '/')} | ${j.how} |`);
  md.push('');
}
md.push('## Coverage', '', '| Company | Tier | Board | Open (all) | Matched |', '|---|---|---|---|---|');
for (const s of status) md.push(`| ${s.name} | T${s.tier} | ${s.ats ? `${s.ats}/${s.slug.split("|")[0]}` : '—'} | ${s.total ?? '—'} | ${s.state === 'ok' ? s.matched : s.state} |`);
writeFileSync(new URL(`./JOBS-${region.toUpperCase()}.md`, import.meta.url), md.join('\n') + '\n');
console.log(`${jobs.length} roles from ${status.filter((s) => s.state === 'ok').length}/${status.length} companies`);
for (const t of ['ui', 'node', 'java', 'fullstack', 'other-eng']) console.log(t, jobs.filter((j) => j.track === t).length);
